### ISSUE TITLE
Error when upgrade Angular 2.0.0-beta.13 to 2.0.0-rc.1

### ISSUE THREAD

**Issue by lhpkhanh** [mgechev/angular2-seed#887]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

When i upgrade, i see error:
+ In Commandline
`D:/nodejs/sb-ng2-client/node_modules/rxjs/add/operator/map.d.ts(2,16): error TS2435: Ambient modules cannot be nested in other modules or namespaces.
D:/nodejs/sb-ng2-client/node_modules/rxjs/add/operator/map.d.ts(2,16): error TS2436: Ambient module declaration cannot specify relative module name.
src\directives\auth-router-outlet\auth-router-outlet.ts(20,11): error TS2345: Argument of type 'ElementRef' is not assignable to parameter of type 'ViewContainerRef'.
  Property 'element' is missing in type 'ElementRef'.
src\main.ts(6,9): error TS2305: Module '"D:/nodejs/sb-ng2-client/node_modules/@angular/router-deprecated/index"' has no exported member 'APP_BASE_HREF'.
src\main.ts(6,42): error TS2305: Module '"D:/nodejs/sb-ng2-client/node_modules/@angular/router-deprecated/index"' has no exported member 'LocationStrategy'.
src\main.ts(6,60): error TS2305: Module '"D:/nodejs/sb-ng2-client/node_modules/@angular/router-deprecated/index"' has no exported member 'PathLocationStrategy'.`

+systemjs.config.js:
`System.config({
    transpiler: 'typescript',
    typescriptOptions: {emitDecoratorMetadata: true},
    map: {
        'app' : 'app',
        'rxjs': '/node_modules/rxjs',
        '@angular'                    : '/node_modules/@angular',
        '@angular/core'                    : '/node_modules/@angular/core',
        '@angular/common'                  : '/node_modules/@angular/common',
        '@angular/compiler'                : '/node_modules/@angular/compiler',
        '@angular/router-deprecated'                  : '/node_modules/@angular/router-deprecated',
        '@angular/platform-browser'        : '/node_modules/@angular/platform-browser',
        '@angular/platform-browser-dynamic': '/node_modules/@angular/platform-browser-dynamic'
      },
      packages: {
        'app'                              : {main: 'main.ts', defaultExtension: 'ts'},
        'rxjs'                             : {main: 'index.js'},
        '@angular/core'                    : {main: 'index.js'},
        '@angular/common'                  : {main: 'index.js'},
        '@angular/compiler'                : {main: 'index.js'},
        '@angular/router-deprecated'       : {main: 'index.js'},
        '@angular/platform-browser'        : {main: 'index.js'},
        '@angular/platform-browser-dynamic': {main: 'index.js'}
      }
});`

+ config.ts
`...
{ src: `${ASSETS_SRC}/js/systemjs.config.js`, inject: 'libs', dest: JS_DEST }
...`

+ package.json:
`...
"dependencies": {
    "angular2": "2.0.0-beta.13",
    "angular2-notifications": "0.1.47",
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.1",
    "@angular/upgrade": "2.0.0-rc.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "^0.19.27",
    "zone.js": "^0.6.12",
    "async": "^1.5.2"
  }
...`

pls tell me, which error and fixed?
**Current behavior**

**Expected/desired behavior**

**Other information**

**Comment by TheDonDope** [comment]
Hi @lhpkhanh, 
on which commit of the seed is your code based on?  The SystemJS configuration of the seed is done in `seed.config.ts`(https://github.com/mgechev/angular2-seed/blob/master/tools/config/seed.config.ts):

```TypeScript
/**
   * The system builder configuration of the application.
   * @type {any}
   */
  SYSTEM_BUILDER_CONFIG: any = {
    defaultJSExtensions: true,
    packageConfigPaths: [
      join(this.PROJECT_ROOT, 'node_modules', '*', 'package.json'),
      join(this.PROJECT_ROOT, 'node_modules', '@angular', '*', 'package.json')
    ],
    paths: {
      [`${this.TMP_DIR}/*`]: `${this.TMP_DIR}/*`,
      '*': 'node_modules/*'
    },
    packages: {
      '@angular/core': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/compiler': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/common': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/http': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/platform-browser': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/platform-browser-dynamic': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/router-deprecated': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      '@angular/router': {
        main: 'index.js',
        defaultExtension: 'js'
      },
      'rxjs': {
        defaultExtension: 'js'
      }
    }
  };
```


Did you write your `systemjs.config.js` yourself or is it a generated file?
Can you try to do a fresh clone of the seed with the latest commit (https://github.com/mgechev/angular2-seed/commit/591a57226bf95bc3d14e443c86b38092dcd6ed73) and try to reproduce it again?

Greetings

Dope

**Comment by lhpkhanh** [comment]
I do it and rebuild, but still error:
-------------CMD-------------------------
$ npm install
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will
fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon
as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained.
Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will
fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon
as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network
settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

.....

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6

npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\nodejs\sb-ng2-client\npm-debug.log

pls help me with error

Thanks!

2016-05-17 18:17 GMT+07:00 Christian Dobert <notifications@github.com>:

**Comment by TheDonDope** [comment]
Hi @lhpkhanh,

just as the log output says: This is most likely not a problem with npm, but rather with a bad network connection:

```bash
npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network
settings.
```

This issue is not related to `angular2-seed`

**Comment by lhpkhanh** [comment]
Error when i run server on CMD:

`D:/nodejs/sb-ng2-client/node_modules/rxjs/add/operator/map.d.ts(2,16): error TS2435: Ambient modules cannot be nested in other modules or namespaces.
D:/nodejs/sb-ng2-client/node_modules/rxjs/add/operator/map.d.ts(2,16): error TS2436: Ambient module declaration cannot specify relative module name.
src\directives\auth-router-outlet\auth-router-outlet.ts(20,11): error TS2345: Argument of type 'ElementRef' is not assignable to parameter of type 'ViewContainerRef'.
  Property 'element' is missing in type 'ElementRef'.
src\main.ts(6,9): error TS2305: Module '"D:/nodejs/sb-ng2-client/node_modules/@angular/router-deprecated/index"' has no exported member 'APP_BASE_HREF'.
src\main.ts(6,42): error TS2305: Module '"D:/nodejs/sb-ng2-client/node_modules/@angular/router-deprecated/index"' has no exported member 'LocationStrategy'.
src\main.ts(6,60): error TS2305: Module '"D:/nodejs/sb-ng2-client/node_modules/@angular/router-deprecated/index"' has no exported member 'PathLocationStrategy'.
[13:20:54] TypeScript: 6 semantic errors`

![capture017](https://cloud.githubusercontent.com/assets/19406140/15349391/9900ccfc-1cfc-11e6-8a51-c035fb933399.PNG)

**Comment by TheDonDope** [comment]
Hi @lhpkhanh,

from your console output i can see that there are a few issues (incorrect imports etc.).
But without a look at the sourcecode i'm afraid i cannot help you any further.
Also those issues are not related to `angular2-seed` itself.

This issue should be closed as it is not related to the seed itself.

**Comment by TheDonDope** [comment]
Closing the issue for now, since it is not a seed issue.
